use_frameworks!

target 'Aldo_Example' do
    pod 'MockFive', :git => 'https://github.com/makchich/MockFive.git'
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.0'
  pod 'Aldo', :path => '../'

  target 'Aldo_Tests' do
    inherit! :search_paths

    
  end
end
