language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/Aldo.xcworkspace
  - SCHEME="Aldo-Example"
  - SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 7"
  
notifications:
  email: false

before_install:
  - brew update
  - brew install swiftlint
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES test | xcpretty
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash) -J "Aldo"
