# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/Aldo.xcworkspace
  - SCHEME="Aldo-Example"
  - SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 7"
  
notifications:
  email: false

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
# - xcodebuild test -workspace Example/Aldo.xcworkspace -scheme Aldo-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty

- pod lib lint
